name: SpecialEventPlugin
version: 1.0.0
api-version: 1.15
author: darkenedfusion
description: Creates custom items for Astral SMP
main: io.github.darkenedfusion.SpecialEventPlugin.SpecialEventPlugin
commands:
  cloudboots:
    description: Gives player cloud boots.
    usage: /cloudboots